# Site settings
title: rakun
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/rakun" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: rakun
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: à deux, c’est mieux !

company: 
  twitter: RakunTeam
  github: rakunteam
  linkedin: rakunteam
  email: contact@rakun.team

members:
  - fabien:
    color: purple
    firstname: fabien
    lastname: juif
    title: Développeur
    description: JE SUIS FABIEN !
    twitter: fabienjuif
    github: fabienjuif
    linkedin: fabienjuif
    email: fabien.juif@rakun.team
    picture: "https://secure.gravatar.com/avatar/963e047fe4332aaca53a6e5c6d275a1f?s=500"
  - guillaume:
    color: blue
    firstname: guillaume
    lastname: crespel
    title: Développeur
    description: JE SUIS Guillaume !
    twitter: guillaumcrespel
    github: guillaumecrespel
    linkedin: guillaume-crespel
    email: guillaume.crespel@rakun.team
    picture: "https://secure.gravatar.com/avatar/5e688e29837dd60ffc5d497b915ee5f3?s=500"


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
